import canonicalLaneMathlib.AdmissibleClass
import DynamicalSystemsClassicalCelestialMechanicsTheoremCanonicalLaneLean.EulerLagrangeEquations
import DynamicalSystemsClassicalCelestialMechanicsTheoremCanonicalLaneLean.HamiltonianFormulation

namespace HautevilleHouse
namespace DynamicalSystemsClassicalCelestialMechanicsTheoremCanonicalLaneLean

def ConstrainedCelestialMechanicsClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_celestial_mechanics_endgame (A : AdmissibleClass) : ConstrainedCelestialMechanicsClosure A :=
  And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DynamicalSystemsClassicalCelestialMechanicsTheoremCanonicalLaneLean
end HautevilleHouse